import sys
from typing import List

# Import our custom modules
import config
from state import Question, AgentState
from grader_tool import grade_exam
from pprint import pprint

# Define a set of mock questions to simulate the exam generated by Tool 2 (Exam Generator)
MOCK_EXAM: List[Question] = [
    {
        "id": 1,
        "question": "Which component in a RAG system is responsible for converting text chunks into dense vector representations?",
        "options": {
            "a": "Vector Database (e.g., Qdrant)",
            "b": "Embedding Model (e.g., text-embedding-3-small)",
            "c": "Document Parser",
            "d": "Generator LLM"
        },
        "topic": "RAG Embeddings",
        "correct_option": "b"
    },
    {
        "id": 2,
        "question": "In LangGraph, how is the state carried and updated across different nodes of the workflow graph?",
        "options": {
            "a": "Stored in an external SQL database on each step",
            "b": "Passed via function return values only, without preservation",
            "c": "Maintained in a central AgentState dictionary updated by node returns",
            "d": "Held in global variables within the main python module"
        },
        "topic": "LangGraph AgentState",
        "correct_option": "c"
    },
    {
        "id": 3,
        "question": "Which Tavily parameter restricts the search results to specific domains like coursera.org?",
        "options": {
            "a": "domain_filter",
            "b": "exclude_domains",
            "c": "restrict_to",
            "d": "include_domains"
        },
        "topic": "Tavily Search API",
        "correct_option": "d"
    },
    {
        "id": 4,
        "question": "What is the primary function of a Vector Database in a RAG pipeline?",
        "options": {
            "a": "To fine-tune the generator model weights",
            "b": "To store and efficiently perform similarity search over embeddings",
            "c": "To parse PDF files into plain text paragraphs",
            "d": "To compile Python code to machine instructions"
        },
        "topic": "RAG Vector DB",
        "correct_option": "b"
    },
    {
        "id": 5,
        "question": "What does the ReAct design pattern stand for in agentic systems?",
        "options": {
            "a": "Reaction and Activation",
            "b": "Reasoning and Acting",
            "c": "Read and Action",
            "d": "Recursive Activation"
        },
        "topic": "LangGraph ReAct agent",
        "correct_option": "b"
    }
]

def print_exam_contents(exam: List[Question]):
    """Helper to display the generated exam in the console."""
    print("=" * 60)
    print("                  EduMentor AI Mock Exam")
    print("=" * 60)
    for q in exam:
        print(f"\nQ{q['id']}. {q['question']}")
        print(f"Topic: {q['topic']}")
        for opt_key, opt_val in q['options'].items():
            print(f"  {opt_key}) {opt_val}")
    print("=" * 60)



def print_state_summary(state):
    """Pretty-print the adaptive learning state."""

    print("\n" + "=" * 70)
    print("CURRENT ADAPTIVE LEARNING STATE")
    print("=" * 70)

    print("\n===== Learner Profile =====")
    pprint(state["learner_profile"])

    print("\n===== Exam History =====")
    pprint(state["exam_history"])

    print("\n===== Next Exam Focus =====")
    pprint(state["next_exam_focus"])

    print("=" * 70)


def run_exam(state, student_response: str, exam_number: int):
    """Run one exam attempt."""

    print("\n" + "#" * 80)
    print(f"EXAM ATTEMPT #{exam_number}")
    print("#" * 80)

    print(f"\nStudent Answers:\n{student_response}")

    result = grade_exam.func(
        student_answers=student_response,
        state=state
    )

    print("\nREPORT")
    print("-" * 80)
    print(result)

    print_state_summary(state)


def main():

    print("\nStarting EduMentor AI Adaptive Learning Simulation\n")

    print_exam_contents(MOCK_EXAM)

    # ---------------------------------------------------
    # Create ONE persistent state
    # ---------------------------------------------------

    mock_state = {
        "messages": [],
        "active_exam": MOCK_EXAM,
        "learner_profile": {},
        "exam_history": [],
        "next_exam_focus": []
    }

    tavily_configured = (
        config.TAVILY_API_KEY and
        config.TAVILY_API_KEY != "your_tavily_api_key_here"
    )

    llm_configured = (
        (config.GEMINI_API_KEY and
         config.GEMINI_API_KEY != "your_gemini_api_key_here")
        or
        (config.OPENAI_API_KEY and
         config.OPENAI_API_KEY != "your_openai_api_key_here")
    )

    print("\nAPI Status")
    print("-" * 30)
    print(f"Tavily : {'LIVE' if tavily_configured else 'MOCK'}")
    print(f"LLM    : {'LIVE' if llm_configured else 'STATIC'}")

    # ---------------------------------------------------
    # Three exam attempts
    # ---------------------------------------------------

    responses = [

        # Exam 1
        # Miss Q3 and Q4
        "1-b,2-c,3-a,4-d,5-b",

        # Exam 2
        # Miss only Q5
        "1-b,2-c,3-d,4-b,5-a",

        # Exam 3
        # Miss Q1 and Q2
        "1-a,2-a,3-d,4-b,5-b"

    ]

    for exam_number, response in enumerate(responses, start=1):

        run_exam(
            state=mock_state,
            student_response=response,
            exam_number=exam_number
        )

    # ---------------------------------------------------
    # Final dashboard
    # ---------------------------------------------------

    print("\n" + "=" * 80)
    print("FINAL STUDENT PROFILE")
    print("=" * 80)

    print_state_summary(mock_state)

    print("\nExam Count :", len(mock_state["exam_history"]))

    if mock_state["exam_history"]:
        print("Latest Score:",
              mock_state["exam_history"][-1]["score"])

    print("\nNext Adaptive Exam Should Focus On:")

    for topic in mock_state["next_exam_focus"]:
        print(f" • {topic}")

    # ---------------------------------------------------

    print("\n" + "=" * 80)

    try:
        from grader_agent import get_grader_agent

        print("✓ deepagents imported successfully")
        print("✓ Agent loader ready")

    except ImportError:

        print("deepagents is not installed.")

    print("=" * 80)


if __name__ == "__main__":
    main()