import sys
from typing import List

# Import our custom modules
import config
from state import Question, AgentState
from grader_tool import grade_exam

# Define a set of mock questions to simulate the exam generated by Tool 2 (Exam Generator)
MOCK_EXAM: List[Question] = [
    {
        "id": 1,
        "question": "Which component in a RAG system is responsible for converting text chunks into dense vector representations?",
        "options": {
            "a": "Vector Database (e.g., Qdrant)",
            "b": "Embedding Model (e.g., text-embedding-3-small)",
            "c": "Document Parser",
            "d": "Generator LLM"
        },
        "topic": "RAG Embeddings",
        "correct_option": "b"
    },
    {
        "id": 2,
        "question": "In LangGraph, how is the state carried and updated across different nodes of the workflow graph?",
        "options": {
            "a": "Stored in an external SQL database on each step",
            "b": "Passed via function return values only, without preservation",
            "c": "Maintained in a central AgentState dictionary updated by node returns",
            "d": "Held in global variables within the main python module"
        },
        "topic": "LangGraph AgentState",
        "correct_option": "c"
    },
    {
        "id": 3,
        "question": "Which Tavily parameter restricts the search results to specific domains like coursera.org?",
        "options": {
            "a": "domain_filter",
            "b": "exclude_domains",
            "c": "restrict_to",
            "d": "include_domains"
        },
        "topic": "Tavily Search API",
        "correct_option": "d"
    },
    {
        "id": 4,
        "question": "What is the primary function of a Vector Database in a RAG pipeline?",
        "options": {
            "a": "To fine-tune the generator model weights",
            "b": "To store and efficiently perform similarity search over embeddings",
            "c": "To parse PDF files into plain text paragraphs",
            "d": "To compile Python code to machine instructions"
        },
        "topic": "RAG Vector DB",
        "correct_option": "b"
    },
    {
        "id": 5,
        "question": "What does the ReAct design pattern stand for in agentic systems?",
        "options": {
            "a": "Reaction and Activation",
            "b": "Reasoning and Acting",
            "c": "Read and Action",
            "d": "Recursive Activation"
        },
        "topic": "LangGraph ReAct agent",
        "correct_option": "b"
    }
]

def print_exam_contents(exam: List[Question]):
    """Helper to display the generated exam in the console."""
    print("=" * 60)
    print("                  EduMentor AI Mock Exam")
    print("=" * 60)
    for q in exam:
        print(f"\nQ{q['id']}. {q['question']}")
        print(f"Topic: {q['topic']}")
        for opt_key, opt_val in q['options'].items():
            print(f"  {opt_key}) {opt_val}")
    print("=" * 60)

def main():
    print("Starting EduMentor AI Grader Agent Simulation...\n")

    # 1. Show the exam content
    print_exam_contents(MOCK_EXAM)

    # 2. Setup mock state
    mock_state = {
        "messages": [],
        "active_exam": MOCK_EXAM
    }

    # 3. Simulate student submission in chat
    # In this response, student gets Q1, Q2, and Q5 correct, but misses Q3 and Q4.
    student_response = "1-b, 2-c, 3-a, 4-d, 5-b"
    print(f"\n[Student Chat Input]: \"{student_response}\"")
    print("Processing answers...")

    # Check if API Keys are configured
    tavily_configured = config.TAVILY_API_KEY and config.TAVILY_API_KEY != "your_tavily_api_key_here"
    llm_configured = (config.GEMINI_API_KEY and config.GEMINI_API_KEY != "your_gemini_api_key_here") or \
                     (config.OPENAI_API_KEY and config.OPENAI_API_KEY != "your_openai_api_key_here")

    print("\nAPI Integration Status:")
    print(f"- Tavily Search: {'LIVE' if tavily_configured else 'FALLBACK (MOCK)'}")
    print(f"- LLM Explanations: {'LIVE' if llm_configured else 'FALLBACK (STATIC)'}")

    # 4. Invoke the grader tool logic directly (with injected state)
    # Since 'state' is an injected parameter hidden from the tool schema, we invoke
    # the underlying Python function directly via .func to bypass schema validation
    # during standalone simulation.
    result_markdown = grade_exam.func(student_answers=student_response, state=mock_state)

    print("\n[Grader Agent Response Report]:")
    print(result_markdown)

    # 5. Try importing deepagents to show loader works
    print("\n" + "=" * 60)
    try:
        from grader_agent import get_grader_agent
        print("Success: LangChain 'deepagents' module imported successfully!")
        print("To load the agent, call: agent = get_grader_agent()")
    except ImportError:
        print("Note: 'deepagents' package is not installed in this environment.")
        print("Ensure 'pip install deepagents' is run to wire the agent wrapper.")
    print("=" * 60)

if __name__ == "__main__":
    main()
