from typing import TypedDict, List, Dict, Optional, Annotated
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class Question(TypedDict):
    """
    Schema representing a single multiple-choice question (MCQ) generated by the assistant.
    """
    id: int                   # Question number/identifier, e.g., 1, 2
    question: str             # The actual text of the question
    options: Dict[str, str]   # Dictionary mapping options (e.g., "a", "b", "c", "d") to text
    topic: str                # Topic category for course recommendation, e.g., "RAG Vector DB"
    correct_option: str       # Correct option key, e.g., "b"


class TopicPerformance(TypedDict):
    """
    Cumulative performance tracking for a single topic across all exams.
    """
    attempts: int       # Total questions attempted for this topic
    correct: int        # Total correct answers for this topic
    accuracy: float     # Computed as (correct / attempts) * 100


class ExamRecord(TypedDict):
    """
    Historical record of a single completed exam session.
    """
    timestamp: str              # ISO-format datetime string when the exam was graded
    score: float                # Percentage score (0–100)
    total_questions: int        # Number of questions in the exam
    weak_topics: List[str]      # Topics where the student made mistakes


class AgentState(TypedDict):
    """
    Agent State carried across LangGraph execution steps.

    Backward-compatible extension: all new fields are Optional so existing
    state objects loaded from older snapshots will not crash.
    """
    messages: Annotated[List[BaseMessage], add_messages]

    # Written by Tool 2 (Exam Generator); read by Tool 3 (Grader)
    active_exam: Optional[List[Question]]

    # Cumulative topic-level performance; keyed by topic string
    learner_profile: Optional[Dict[str, TopicPerformance]]

    # Ordered list of completed exam records (capped at 50)
    exam_history: Optional[List[ExamRecord]]

    # Weakest topics surfaced for Tool 2 to prioritise in the next exam
    next_exam_focus: Optional[List[str]]