from typing import TypedDict, List, Dict, Optional, Annotated
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class Question(TypedDict):
    """
    Schema representing a single multiple-choice question (MCQ) generated by the assistant.
    """
    id: int                   # Question number/identifier, e.g., 1, 2
    question: str             # The actual text of the question
    options: Dict[str, str]   # Dictionary mapping options (e.g., "a", "b", "c", "d") to text
    topic: str                # Topic category for course recommendation, e.g., "RAG Vector DB"
    correct_option: str       # Correct option key, e.g., "b"

class AgentState(TypedDict):
    """
    Agent State carried across LangGraph execution steps.
    """
    messages: Annotated[List[BaseMessage], add_messages]
    active_exam: Optional[List[Question]]
